/**
 * F5.6 C7-H1 Finance OS — Finance Kernel Client Implementation
 * 
 * Wraps F1-F4 Finance Kernel (Ledger Engine) for Finance OS
 * 
 * Architecture Boundary:
 * - Input: Posting instruction (balanced entries)
 * - Output: Finance transaction (from Kernel)
 * 
 * Responsibilities:
 * - Convert posting instruction → PostTransactionRequest (Kernel format)
 * - Call existing Ledger Engine
 * - Handle Kernel responses/errors
 * 
 * Does NOT:
 * - Modify Kernel
 * - Validate business logic (that's Finance OS responsibility)
 * - Resolve semantic/intent/COA (done upstream)
 * 
 * @see src/platform/finance/engines/ledger-engine
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database, Json } from '@/types/database.types';
import type { FinanceKernelClient, PostingInstruction, FinanceTransaction } from '../finance-event-handler';

/**
 * Default Finance Kernel Client
 * 
 * Wraps existing F1-F4 Ledger Engine
 * 
 * Converts Finance OS posting instruction → Kernel transaction request
 */
export class DefaultFinanceKernelClient implements FinanceKernelClient {
  constructor(private supabase: SupabaseClient<Database>) {}
  
  /**
   * Persist posting instruction to F1-F4 Kernel
   * 
   * @param instruction Posting instruction (from Finance OS)
   * @returns Finance transaction (from Kernel)
   */
  async persist(instruction: PostingInstruction): Promise<FinanceTransaction> {
    // Convert posting instruction → Kernel request format
    const kernelRequest = await this.convertToKernelRequest(instruction);
    
    // Insert journal entry (header)
    const { data: journalEntry, error: entryError } = await this.supabase
      .from('journal_entries')
      .insert({
        tenant_id: kernelRequest.tenant_id,
        description: kernelRequest.description,
        entry_date: kernelRequest.entry_date,
        reference_type: kernelRequest.reference_type,
        reference_id: kernelRequest.reference_id, // Will be UUID generated by DB
        status: kernelRequest.status,
      })
      .select()
      .single();
    
    if (entryError || !journalEntry) {
      throw new KernelPersistenceError(
        `Failed to create journal entry: ${entryError?.message}`,
        instruction,
        entryError
      );
    }
    
    // Insert journal lines (Dr/Cr)
    const { error: linesError } = await this.supabase
      .from('journal_lines')
      .insert(
        kernelRequest.lines.map((line: any) => ({
          entry_id: journalEntry.id,
          account_id: line.account_id,
          debit_amount: line.debit_amount,
          credit_amount: line.credit_amount,
        }))
      );
    
    if (linesError) {
      throw new KernelPersistenceError(
        `Failed to create journal lines: ${linesError.message}`,
        instruction,
        linesError
      );
    }
    
    // N3: Store immutable transaction metadata
    const { error: metadataError } = await this.supabase
      .from('finance_transaction_metadata')
      .insert({
        journal_entry_id: journalEntry.id,
        event_id: instruction.source_event_id,
        tenant_id: instruction.tenant_id,
        canonical_semantic: instruction.metadata?.canonical_semantic || 'UNKNOWN',
        semantic_category: instruction.metadata?.semantic_category || 'UNKNOWN',
        accounting_intents: (instruction.metadata?.accounting_intents || []) as unknown as Json,
        policy_version: instruction.metadata?.policy_version || 'v1.0',
        policy_regime: instruction.metadata?.policy_regime || 'DEFAULT',
        coa_version: instruction.metadata?.coa_version || 'v1.0',
        posting_context: (instruction.business_context || {}) as Json,
        account_mappings: (instruction.metadata?.account_mappings || []) as unknown as Json,
        source_system: instruction.source_system,
        source_version: instruction.metadata?.source_version || '1.0.0',
        transaction_date: instruction.transaction_date,
      });
    
    if (metadataError) {
      console.error('[KernelClient] Failed to store metadata:', metadataError);
      // Don't fail transaction - metadata is audit/historical, not critical for posting
    }
    
    // Return finance transaction
    return {
      transaction_id: journalEntry.id,
      status: 'COMMITTED',
    };
  }
  
  /**
   * Convert posting instruction → Kernel request format
   * 
   * Maps Finance OS format → F1-F4 Ledger Engine format
   * 
   * CRITICAL: Kernel uses journal_entries + journal_lines schema:
   * - Amount: number (major units, NOT minor)
   * - Account: account_id (FK, NOT account_code)
   * - Source: reference_id (UUID) + reference_type
   * - Event ID: Stored in description for traceability
   */
  private async convertToKernelRequest(instruction: PostingInstruction): Promise<any> {
    // Resolve account_code → account_id for each entry
    const linesWithAccountIds = await Promise.all(
      instruction.entries.map(async (entry) => {
        // Lookup account_id from account_code
        const { data: account } = await this.supabase
          .from('accounting_accounts')
          .select('id')
          .eq('account_code', entry.account_id) // entry.account_id is actually account_code from COA resolver
          .eq('tenant_id', instruction.tenant_id)
          .single();
        
        if (!account) {
          throw new Error(`Account not found: code=${entry.account_id}, tenant=${instruction.tenant_id}`);
        }
        
        return {
          account_id: account.id, // UUID
          debit_amount: parseFloat(entry.debit), // Major units (500000 = 500k VND)
          credit_amount: parseFloat(entry.credit),
          memo: entry.description || '',
        };
      })
    );
    
    // Create journal entry (header)
    // NOTE: reference_id is UUID - for now, leave NULL and store event_id in description
    // Future: Create finance_events table to map event_id → journal_entry_id
    return {
      tenant_id: instruction.tenant_id,
      description: `${this.generateDescription(instruction)} [Event: ${instruction.source_event_id}]`,
      entry_date: new Date(instruction.transaction_date).toISOString(),
      reference_type: 'FINANCE_EVENT',
      reference_id: null, // NULL for now (schema expects UUID)
      status: 'POSTED',
      lines: linesWithAccountIds,
    };
  }
  
  /**
   * Generate transaction description
   */
  private generateDescription(instruction: PostingInstruction): string {
    const context = instruction.business_context as Record<string, unknown>;
    
    // Try to extract meaningful description from business context
    if (context?.patient) {
      const patient = context.patient as Record<string, unknown>;
      return `Patient service (${patient.patient_id})`;
    }
    
    if (context?.pharmacy) {
      const pharmacy = context.pharmacy as Record<string, unknown>;
      return `Medication: ${pharmacy.medication_name}`;
    }
    
    if (context?.procurement) {
      const procurement = context.procurement as Record<string, unknown>;
      return `Supplier: ${procurement.supplier_name || 'N/A'}`;
    }
    
    return `Finance transaction (${instruction.source_system})`;
  }
}

/**
 * Kernel Persistence Error
 * 
 * Thrown when Kernel fails to persist transaction
 */
export class KernelPersistenceError extends Error {
  constructor(
    message: string,
    public readonly instruction: PostingInstruction,
    public readonly kernelError?: { code: string; message: string }
  ) {
    super(message);
    this.name = 'KernelPersistenceError';
  }
}
