import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Baseline of files that still contain `any` as of Phase 1.1.5 (2026-05-28).
// These are downgraded to `warn` so existing debt does not break CI, while every
// other file gets `error` — meaning any NEW `as any` in clean code fails the build.
// Shrink this list as files are cleaned (Sprint 1.3 file splits will remove many).
const ANY_DEBT_BASELINE = [
  "src/adapters/__tests__/commission-provider-adapter.test.ts",
  "src/app/(auth)/signup/page.tsx",
  "src/app/api/admin/booking-engine/metrics/route.ts",
  "src/app/api/cron/accounting-worker/route.ts",
  "src/app/api/cron/ai-autopilot/route.ts",
  "src/app/api/cron/gate3-monitor/route.ts",
  "src/app/api/cron/zalo-reminders/route.ts",
  "src/app/api/customers/route.ts",
  "src/app/api/intelligence/forecast/accuracy/route.ts",
  "src/app/api/intelligence/forecast/all/route.ts",
  "src/app/api/intelligence/forecast/churn/route.ts",
  "src/app/api/intelligence/forecast/demand/route.ts",
  "src/app/api/intelligence/forecast/revenue/route.ts",
  "src/app/api/intelligence/recommendation/package/route.ts",
  "src/app/api/intelligence/recommendation/service/route.ts",
  "src/app/api/intelligence/recommendation/upsell/route.ts",
  "src/app/api/metrics/route.ts",
  "src/app/api/packages/route.ts",
  "src/app/api/tenant/context/route.ts",
  "src/app/api/test-upcoming/route.ts",
  "src/app/api/users/route.ts",
  "src/app/api/v1/ai/action-approval/route.ts",
  "src/app/api/v1/ai/coo-orchestrator/route.ts",
  "src/app/api/v1/ai/telegram-webhook/route.ts",
  "src/app/api/waitlist/\\[entryId\\]/route.ts",
  "src/app/api/waitlist/route.ts",
  "src/app/api/webhooks/payment/route.ts",
  "src/app/dashboard/accounting/chart-of-accounts/page.tsx",
  "src/app/dashboard/accounting/journals/\\[entryId\\]/page.tsx",
  "src/app/dashboard/accounting/journals/page.tsx",
  "src/app/dashboard/accounting/manual-entry/page.tsx",
  "src/app/dashboard/accounting/outbox/page.tsx",
  "src/app/dashboard/accounting/page.tsx",
  "src/app/dashboard/accounting/periods/page.tsx",
  "src/app/dashboard/accounting/reconciliation/page.tsx",
  "src/app/dashboard/accounting/reports/page.tsx",
  "src/app/dashboard/accounting/salary-reconciliation/page.tsx",
  "src/app/dashboard/ai-copilot/ai-copilot-client.tsx",
  "src/app/dashboard/bookings/page.tsx",
  "src/app/dashboard/chat/page.tsx",
  "src/app/dashboard/crm/page.tsx",
  "src/app/dashboard/customer/page.tsx",
  "src/app/dashboard/customers/\\[id\\]/page.tsx",
  "src/app/dashboard/customers/page.tsx",
  "src/app/dashboard/finance/budget/page.tsx",
  "src/app/dashboard/finance/page.tsx",
  "src/app/dashboard/finance/reconciliation/page.tsx",
  "src/app/dashboard/forecast/page.tsx",
  "src/app/dashboard/inventory/page.tsx",
  "src/app/dashboard/page.tsx",
  "src/app/dashboard/recommendations/page.tsx",
  "src/app/dashboard/rules/\\[ruleId\\]/page.tsx",
  "src/app/dashboard/rules/\\[ruleId\\]/test/page.tsx",
  "src/app/dashboard/rules/\\[ruleId\\]/versions/page.tsx",
  "src/app/dashboard/services/page.tsx",
  "src/app/dashboard/sessions/components/LeaveApprovalModal.tsx",
  "src/app/dashboard/sessions/components/SessionLogsDetailsModal.tsx",
  "src/app/dashboard/sessions/page.tsx",
  "src/app/dashboard/settings/PermissionsTab.tsx",
  "src/app/dashboard/settings/components/AccountingConfigTab.tsx",
  "src/app/dashboard/settings/components/CommissionSettingsTab.tsx",
  "src/app/dashboard/settings/components/HqBillingTab.tsx",
  "src/app/dashboard/settings/components/SalaryConfigTab.tsx",
  "src/app/dashboard/settings/components/SubscriptionTab.tsx",
  "src/app/hq/financial-overview/page.tsx",
  "src/app/hq/hq-dashboard-client.tsx",
  "src/app/ktv/dashboard/page.tsx",
  "src/app/ktv/earnings/page.tsx",
  "src/app/ktv/leaderboard/page.tsx",
  "src/app/page.tsx",
  "src/app/portal/\\[token\\]/page.tsx",
  "src/components/bookings/ServiceItemRow.tsx",
  "src/components/bookings/__examples__/ServiceItemRowExample.tsx",
  "src/components/common/PwaRegister.tsx",
  "src/components/decision-engine/DecisionDetailDrawer.tsx",
  "src/components/decision-engine/DecisionHistoryTimeline.tsx",
  "src/components/decision-engine/DecisionTimeMachine.tsx",
  "src/components/features/BookingModal.tsx",
  "src/components/features/QuickAddCustomerModal.tsx",
  "src/components/features/TransactionModal.tsx",
  "src/components/features/landing/ServiceWizard.tsx",
  "src/components/features/portal/PortalChatWidget.tsx",
  "src/components/finance/charts.tsx",
  "src/components/intelligence/BudgetStatusChart.tsx",
  "src/components/intelligence/ExpenseBreakdownChart.tsx",
  "src/components/intelligence/RevenueBreakdownChart.tsx",
  "src/components/intelligence/customer/ChurnRiskChart.tsx",
  "src/components/intelligence/customer/CustomerActivityChart.tsx",
  "src/components/intelligence/customer/LtvByCohortChart.tsx",
  "src/components/intelligence/customer/LtvDistributionChart.tsx",
  "src/components/layout/sidebar.tsx",
  "src/components/product-sales/ProductSalesListPage.tsx",
  "src/components/rules/ActionRow.tsx",
  "src/components/rules/__tests__/RuleEditor.test.tsx",
  "src/core/examples/TenantInfoExample.tsx",
  "src/core/middleware/tenantContext.test.ts",
  "src/core/middleware/tenantContext.ts",
  "src/core/providers/TenantContextProvider.tsx",
  "src/core/services/analytics/dashboard-actions.ts",
  "src/core/services/finance/monthly-pnl-report.ts",
  "src/core/services/order/pricing-actions.test.ts",
  "src/cron/sync-external-ads.ts",
  "src/hooks/intelligence/use-finance.ts",
  "src/hooks/intelligence/use-forecast.ts",
  "src/hooks/intelligence/use-recommendation.ts",
  "src/hooks/useOfflineSync.ts",
  "src/lib/__mocks__/supabase-server.ts",
  "src/lib/accounting-outbox.ts",
  "src/lib/business-process/types.ts",
  "src/lib/business-rules/__tests__/commission.test.ts",
  "src/lib/decision-engine/__tests__/integration.test.ts",
  "src/lib/decision-engine/policies/leave-approval-policy.ts",
  "src/lib/decision-engine/providers/booking/__tests__/capacity-management-provider.test.ts",
  "src/lib/decision-engine/providers/booking/auto-assignment-provider.ts",
  "src/lib/decision-engine/providers/booking/capacity-management-provider.ts",
  "src/lib/decision-engine/providers/booking/conflict-detection-provider.ts",
  "src/lib/decision-engine/providers/commission/__tests__/commission-provider.performance.test.ts",
  "src/lib/decision-engine/providers/commission/commission-provider.ts",
  "src/lib/decision-engine/providers/discount/discount-provider.ts",
  "src/lib/decision-engine/providers/payroll/payroll-provider.ts",
  "src/lib/decision-engine/providers/payroll/types.ts",
  "src/lib/decision-engine/registry/__tests__/PolicyRegistry.integration.test.ts",
  "src/lib/decision-engine/registry/__tests__/audit.test.ts",
  "src/lib/decision-engine/registry/__tests__/validation.test.ts",
  "src/lib/decision-engine/registry/archive/PolicyAuditService.ts",
  "src/lib/decision-engine/registry/archive/PolicyGovernanceService.ts",
  "src/lib/decision-engine/registry/archive/PolicyLifecycleService.ts",
  "src/lib/decision-engine/registry/archive/PolicyStatisticsService.ts",
  "src/lib/log-redactor.ts",
  "src/lib/offline-db.ts",
  "src/lib/subscription.ts",
  "src/lib/utils.ts",
  "src/lib/workflow-engine/__tests__/workflow-engine.test.ts",
  "src/modules/booking/actions/commission-actions.ts",
  "src/modules/booking/actions/session-actions.ts",
  "src/modules/bookings/actions/__tests__/ktv-suggestion-actions.test.ts",
  "src/modules/bookings/actions/ktv-suggestion-actions.ts",
  "src/services/ai-coo-service.ts",
  "src/services/attendance-actions.ts",
  "src/services/audit-actions.ts",
  "src/services/booking-decision.service.ts",
  "src/services/brand-service-actions.ts",
  "src/services/chat-actions.ts",
  "src/services/clearing-actions.ts",
  "src/services/crm-actions.ts",
  "src/services/customer-actions.ts",
  "src/services/decision-actions/__tests__/booking-decisions.test.ts",
  "src/services/export-actions.ts",
  "src/services/franchise-actions.ts",
  "src/services/intelligence/__tests__/helpers/test-utils.ts",
  "src/services/intelligence/__tests__/integration/forecast-api.test.ts",
  "src/services/intelligence/__tests__/multi-tier-cache.test.ts",
  "src/services/intelligence/cache/memory-cache.ts",
  "src/services/intelligence/customer/__tests__/benchmark.ts",
  "src/services/intelligence/customer/__tests__/integration.test.ts",
  "src/services/intelligence/customer/queries.ts",
  "src/services/intelligence/events/event-listener.ts",
  "src/services/intelligence/executive/__tests__/integration.test.ts",
  "src/services/intelligence/executive/__tests__/queries.test.ts",
  "src/services/intelligence/executive/queries.ts",
  "src/services/intelligence/executive/service.ts",
  "src/services/intelligence/finance/balance-sheet.ts",
  "src/services/intelligence/finance/queries.ts",
  "src/services/intelligence/finance/service.ts",
  "src/services/intelligence/forecast/churn-forecast.ts",
  "src/services/intelligence/forecast/demand-forecast.ts",
  "src/services/intelligence/forecast/revenue-forecast.ts",
  "src/services/intelligence/forecast/service.ts",
  "src/services/intelligence/hr/__tests__/benchmark.ts",
  "src/services/intelligence/hr/__tests__/integration.test.ts",
  "src/services/intelligence/hr/queries-simple.ts",
  "src/services/intelligence/hr/queries.ts",
  "src/services/intelligence/hr/service.ts",
  "src/services/intelligence/marketing/__tests__/connectors.test.ts",
  "src/services/intelligence/marketing/cache.ts",
  "src/services/intelligence/marketing/connectors/base.ts",
  "src/services/intelligence/marketing/connectors/facebook-ads.ts",
  "src/services/intelligence/marketing/connectors/zalo-oa.ts",
  "src/services/intelligence/marketing/queries.ts",
  "src/services/intelligence/marketing/service.ts",
  "src/services/intelligence/marketing/types.ts",
  "src/services/intelligence/operational/__tests__/integration.test.ts",
  "src/services/intelligence/operational/__tests__/service.test.ts",
  "src/services/intelligence/operational/queries.ts",
  "src/services/intelligence/operational/service.ts",
  "src/services/intelligence/recommendation/package-recommendation.ts",
  "src/services/intelligence/recommendation/service-recommendation.ts",
  "src/services/intelligence/recommendation/service.ts",
  "src/services/intelligence/recommendation/upsell-recommendation.ts",
  "src/services/intelligence/shared/types.ts",
  "src/services/inventory-actions.ts",
  "src/services/inventory-transfer-actions.ts",
  "src/services/ktv-actions.ts",
  "src/services/notifications/notification-service.ts",
];

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    "e2e/**",
    "mcp-server/**",
    "scripts/**",
    "scratch/**",
    "load-tests/**",
    "coverage/**",
    "playwright-report/**",
    ".tmp/**",
    "temp_output/**",
    "*.js",
    "*.mjs",
    "docs/**/*.js",
    "tests/**",
    "apps/**",
    "archive-old-decision-engine/**",
    "src/app/dashboard/customer/segmentation/page.tsx",
    "src/app/dashboard/settings/components/CommissionSettingsTab.tsx",
    "src/components/intelligence/customer/ChurnRiskChart.tsx",
    "src/components/intelligence/customer/CustomerActivityChart.tsx",
    "src/components/intelligence/customer/LtvByCohortChart.tsx",
    "src/components/intelligence/customer/LtvDistributionChart.tsx",
    "src/components/intelligence/customer/RetentionCurveChart.tsx",
    "src/components/product-sales/ProductSalesListPage.tsx",
    "src/hooks/useProgressiveLoad.ts",
  ]),
  // Phase 1.1.5: no-explicit-any is an ERROR everywhere in production code.
  // A new `as any` in any clean file fails the build. `npm run lint:strict`
  // runs the same gate across the entire tree (including the baseline below).
  {
    files: ["src/**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-explicit-any": "error",
      // Allow unused vars prefixed with underscore (for interface compliance)
      "@typescript-eslint/no-unused-vars": [
        "warn",
        {
          "argsIgnorePattern": "^_",
          "varsIgnorePattern": "^_",
          "caughtErrorsIgnorePattern": "^_"
        }
      ],
      // Data-fetch-on-mount screens intentionally set loading/result state from effects.
      // Keep exhaustive-deps on for stale-closure bugs; avoid noisy false positives here.
      "react-hooks/set-state-in-effect": "off",
      "react/no-unescaped-entities": "warn",
      "prefer-const": "warn",
      "@typescript-eslint/prefer-as-const": "warn",
      "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
      "@typescript-eslint/ban-ts-comment": "warn",
      "react-hooks/rules-of-hooks": "warn",
      "react-hooks/static-components": "warn",
      "react-hooks/preserve-manual-memoization": "warn",
      "react-hooks/refs": "warn",
      "react-hooks/use-memo": "warn",
    },
  },
  // Existing debt: downgrade to warn so CI is not blocked retroactively.
  {
    files: ANY_DEBT_BASELINE,
    rules: {
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  // Test files and setup/config files legitimately use `any` for mocks and `require` for imports — exempt.
  {
    files: [
      "src/__tests__/**/*.{ts,tsx}",
      "src/**/__tests__/**/*.{ts,tsx}",
      "src/**/*.test.{ts,tsx}",
      "jest.setup.ts",
      "instrumentation-client.ts",
      "instrumentation.ts",
      "sentry.edge.config.ts",
      "sentry.server.config.ts",
    ],
    rules: {
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;
