-- Prevent duplicate salary expenses generated by salary approval/finalization workflows.
-- Generated salary expense descriptions include salary_record_id and ktv_id, so tenant + description
-- is the durable business idempotency key for this legacy expenses side effect.
do $$
begin
  if exists (
    select 1
    from public.expenses
    where tenant_id is not null
      and lower(category) = 'salary'
      and coalesce(nullif(btrim(description), ''), '') <> ''
    group by tenant_id, btrim(description)
    having count(*) > 1
  ) then
    raise exception 'Duplicate salary expenses exist by tenant_id and description; resolve them before installing idx_expenses_salary_description_unique.';
  end if;
end $$;

create unique index if not exists idx_expenses_salary_description_unique
on public.expenses (tenant_id, (btrim(description)))
where tenant_id is not null
  and lower(category) = 'salary'
  and coalesce(nullif(btrim(description), ''), '') <> '';
