-- =============================================================================
-- Hotfix: Phase 29.3 — get_consolidated_pnl ambiguous "tenant_id" (no-op)
-- Ngày: 2026-05-25
--
-- Directive #variable_conflict use_column đã được tích hợp trực tiếp vào
-- 20260525190000_consolidated_pnl_hq.sql khi file đó được viết, nên migration
-- này không cần re-create lại toàn bộ function.
--
-- File được giữ lại để đảm bảo tính liên tục của migration sequence.
-- =============================================================================
DO $$ BEGIN NULL; END $$;
